import { Recommendation } from "@/components/ServiceCard";

// Mock Book Again services data
export const bookAgainServices: Recommendation[] = [
  {
    id: 101,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 120,
    categories: ["Barber", "Salon"],
    lastVisited: "Last visited 1 week ago",
    startingPrice: 15,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca"],
    hasDiamond: true,
  },
  {
    id: 102,
    title: "Zara Hair & Beauty | Limassol Marina",
    rating: 4.8,
    reviews: 85,
    categories: ["Hair", "Salon"],
    location: "Limassol Marina",
    distance: "2.5km away",
    lastVisited: "Last visited 3 weeks ago",
    startingPrice: 25,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 103,
    title: "Gold Gym Spa & Massage | Nicosia",
    rating: 4.7,
    reviews: 310,
    categories: ["Massage", "Wellness"],
    location: "Nicosia",
    distance: "5.0km away",
    lastVisited: "Last visited 1 month ago",
    startingPrice: 40,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
  },
  {
    id: 104,
    title: "Elite Car Detailing | Paphos",
    rating: 4.9,
    reviews: 145,
    categories: ["Automotive"],
    location: "Paphos",
    distance: "8.0km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 50,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 105,
    title: "Precision Men's Grooming | Larnaca",
    rating: 4.6,
    reviews: 92,
    categories: ["Barber"],
    lastVisited: "Last visited 2 weeks ago",
    startingPrice: 18,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Nicosia"],
  },
  {
    id: 106,
    title: "Serenity Yoga Studio | Limassol",
    rating: 5.0,
    reviews: 74,
    categories: ["Wellness"],
    location: "Limassol",
    distance: "1.5km away",
    lastVisited: "Last visited 3 days ago",
    startingPrice: 30,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  }
];

// Mock recommendations data
export const recommendations: Recommendation[] = [
  {
    id: 1,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Limasol", "+4 more"],
    hasDiamond: true,
  },
  {
    id: 2,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 3,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Limasol", "+4 more"],
    noDeposit: true,
  },
  {
    id: 4,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
    noDeposit: true,
  },
  {
    id: 5,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
  },
  {
    id: 6,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
    noDeposit: true,
  },
];

// Mock services near you data
export const servicesNearYou: Recommendation[] = [
  {
    id: 11,
    title: "Zara Hair & Beauty Salon | Nicosia Center",
    rating: 4.7,
    reviews: 142,
    categories: ["Salon", "Beauty"],
    location: "Ledra Street, Nicosia",
    distance: "0.8km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 25,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
  },
  {
    id: 12,
    title: "Zen Spa & Massage | Limassol Marina",
    rating: 4.9,
    reviews: 88,
    categories: ["Spa", "Wellness"],
    location: "Marina Road, Limassol",
    distance: "1.5km away",
    lastVisited: "Last visited 3 months ago",
    startingPrice: 60,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 13,
    title: "Elite Barber Studio | Larnaca Bay",
    rating: 4.8,
    reviews: 210,
    categories: ["Barber"],
    travelsToYou: true,
    travelLocations: ["Larnaca", "Dekhelia"],
    lastVisited: "Last visited 2 months ago",
    startingPrice: 18,
    image: "/img/service_demo.jpg",
  },
  {
    id: 14,
    title: "Dynamic Fitness Coach | Paphos District",
    rating: 5.0,
    reviews: 45,
    categories: ["Sports", "Fitness"],
    travelsToYou: true,
    travelLocations: ["Paphos", "Peyia"],
    lastVisited: "Last visited 3 months ago",
    startingPrice: 30,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 15,
    title: "Luxury Nails & Lashes | Limassol",
    rating: 4.6,
    reviews: 95,
    categories: ["Beauty", "Salon"],
    location: "Anexartisias, Limassol",
    distance: "2.1km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 20,
    image: "/img/service_demo.jpg",
  },
  {
    id: 16,
    title: "Pet Care & Grooming | Nicosia",
    rating: 4.9,
    reviews: 120,
    categories: ["Pets"],
    location: "Strovolos, Nicosia",
    distance: "3.5km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 40,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
    noDeposit: true,
  },
];

// Mock popular businesses data (Service cards format)
export const popularBusinesses: Recommendation[] = [
  {
    id: 31,
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Limassol Marina",
    distance: "1.1km away",
    lastVisited: "Popular business",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
    noDeposit: true,
  },
  {
    id: 32,
    title: "Zara Hair & Beauty Salon | Nicosia Center",
    rating: 4.7,
    reviews: 142,
    categories: ["Salon", "Beauty"],
    location: "Ledra Street, Nicosia",
    distance: "0.8km away",
    lastVisited: "Popular business",
    startingPrice: 25,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
  },
  {
    id: 33,
    title: "Zen Spa & Massage | Limassol Marina",
    rating: 4.9,
    reviews: 88,
    categories: ["Spa", "Wellness"],
    location: "Marina Road, Limassol",
    distance: "1.5km away",
    lastVisited: "Popular business",
    startingPrice: 60,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: 34,
    title: "Luxury Nails & Lashes | Limassol",
    rating: 4.6,
    reviews: 95,
    categories: ["Beauty", "Salon"],
    location: "Anexartisias, Limassol",
    distance: "2.1km away",
    lastVisited: "Popular business",
    startingPrice: 20,
    image: "/img/service_demo.jpg",
  },
  {
    id: 35,
    title: "Absolute Tattoo Studio | Ayia Napa",
    rating: 4.8,
    reviews: 320,
    categories: ["Beauty", "Experience"],
    location: "Nissi Avenue, Ayia Napa",
    distance: "0.7km away",
    lastVisited: "Popular business",
    startingPrice: 80,
    image: "/img/service_demo.jpg",
    hasDiamond: true,
  },
  {
    id: 36,
    title: "Precision Men's Grooming | Larnaca",
    rating: 4.6,
    reviews: 92,
    categories: ["Barber"],
    location: "Phinikoudes, Larnaca",
    distance: "1.2km away",
    lastVisited: "Popular business",
    startingPrice: 18,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  }
];
